services:
  client:
    container_name: 'client'
    ports:
      - '80:80'
    build:    
      context: ./client
      dockerfile: Dockerfile
      args:
        API_SERVER: ${API_SERVER}
    networks:
      - mynetworks
    depends_on:
      - app1

  app1:
    container_name: 'app1'
    ports:
      - '5000:5000'
    build:     
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DB_HOST=${Mysql_host}
      - DB_USER=${MySql_Db_User}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_Name=${MySql_Db}
    networks:
      - mynetworks
    depends_on:
      - mysqldb

  mysqldb:
    container_name: 'mysqldb'
    build: 
      context: ./db
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}    
    networks:
      - mynetworks

networks:
  mynetworks:
    driver: bridge
